/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrames;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author divya
 */
public class add_student extends javax.swing.JFrame {

    /**
     * Creates new form add_student
     */
    public add_student() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtosub = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtcno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtdob = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtgender = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtstate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtcity = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtpic = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtfaname = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtfoccupation = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtmname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtmoccupation = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtadddate = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtbusno = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtclass = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtsem = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtbranch = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtlname = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtcoursename = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        submit = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        course = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Home = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        editstudent = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        editfaculty = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        search = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Student");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 230, 40));
        jPanel1.add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 180, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 130, 20));
        jPanel1.add(txtosub, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 180, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Optional Subject");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 130, 20));
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 180, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 130, 20));
        jPanel1.add(txtcno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 180, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contact Number");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 130, 20));
        jPanel1.add(txtdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 180, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date Of Birth");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 130, 20));
        jPanel1.add(txtgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 180, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gender");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 130, 20));
        jPanel1.add(txtstate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 180, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("State");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 130, 20));
        jPanel1.add(txtcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 180, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("City");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 130, 20));
        jPanel1.add(txtpic, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 180, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Picture");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 130, 20));
        jPanel1.add(txtfaname, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 180, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Father Name");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 130, 20));
        jPanel1.add(txtfoccupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 180, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Father Occupation");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 130, 20));
        jPanel1.add(txtmname, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 180, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Mother Name");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 130, 20));
        jPanel1.add(txtmoccupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 180, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Mother Occupation");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 130, 20));
        jPanel1.add(txtadddate, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 180, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Addimission date");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 130, 20));
        jPanel1.add(txtbusno, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 180, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Bus Number");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 130, 20));
        jPanel1.add(txtclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 180, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Class");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 130, 20));
        jPanel1.add(txtsem, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 180, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Semester");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 130, 20));
        jPanel1.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 450, 180, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Password");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 130, 20));
        jPanel1.add(txtbranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 180, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Branch");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 130, 20));
        jPanel1.add(txtlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 180, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Last Name");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 130, 20));
        jPanel1.add(txtcoursename, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 180, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Course Opt");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 130, 20));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submit.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("          Submit");
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                submitMouseExited(evt);
            }
        });
        jPanel2.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 160, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 730, 650));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        course.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        course.setForeground(new java.awt.Color(255, 255, 255));
        course.setIcon(new javax.swing.ImageIcon("C:\\Users\\divya\\Downloads\\myicons\\icons8-teacher-64.png")); // NOI18N
        course.setText("Add Faculty");
        course.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addfacultyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addfacultyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addfacultyMouseExited(evt);
            }
        });
        jPanel4.add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 70));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 170, 70));

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setIcon(new javax.swing.ImageIcon("C:\\Users\\divya\\Downloads\\myicons\\icons8-home-page-100.png")); // NOI18N
        Home.setText("Home");
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeMouseExited(evt);
            }
        });
        jPanel5.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 70));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 170, 70));

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editstudent.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        editstudent.setForeground(new java.awt.Color(255, 255, 255));
        editstudent.setIcon(new javax.swing.ImageIcon("C:\\Users\\divya\\Downloads\\myicons\\icons8-edit-50.png")); // NOI18N
        editstudent.setText("Edit Student");
        editstudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editstudentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editstudentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editstudentMouseExited(evt);
            }
        });
        jPanel6.add(editstudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 70));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 170, 70));

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editfaculty.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        editfaculty.setForeground(new java.awt.Color(255, 255, 255));
        editfaculty.setIcon(new javax.swing.ImageIcon("C:\\Users\\divya\\Downloads\\myicons\\icons8-edit-profile-80.png")); // NOI18N
        editfaculty.setText("Edit Faculty");
        editfaculty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editfacultyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editfacultyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editfacultyMouseExited(evt);
            }
        });
        jPanel7.add(editfaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 180, 70));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 170, 70));

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setIcon(new javax.swing.ImageIcon("C:\\Users\\divya\\Downloads\\myicons\\icons8-search-more-100.png")); // NOI18N
        search.setText("Search");
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchMouseExited(evt);
            }
        });
        jPanel8.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 70));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 170, 70));

        jPanel9.setBackground(new java.awt.Color(0, 102, 102));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("             Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        jPanel9.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 70));

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 170, 70));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 650));

        setSize(new java.awt.Dimension(963, 656));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addfacultyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addfacultyMouseEntered
        Color clr = new Color(0,55,55);
        jPanel4.setBackground(clr);
    }//GEN-LAST:event_addfacultyMouseEntered

    private void addfacultyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addfacultyMouseExited
        Color clr = new Color(0,102,102);
        jPanel4.setBackground(clr);
    }//GEN-LAST:event_addfacultyMouseExited

    private void HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseEntered
        Color clr = new Color(0,55,55);
        jPanel5.setBackground(clr);
    }//GEN-LAST:event_HomeMouseEntered

    private void HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseExited
        Color clr = new Color(0,102,102);
        jPanel5.setBackground(clr);
    }//GEN-LAST:event_HomeMouseExited

    private void editstudentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editstudentMouseEntered
        Color clr = new Color(0,55,55);
        jPanel6.setBackground(clr);
    }//GEN-LAST:event_editstudentMouseEntered

    private void editstudentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editstudentMouseExited
        Color clr = new Color(0,102,102);
        jPanel6.setBackground(clr);
    }//GEN-LAST:event_editstudentMouseExited

    private void editfacultyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editfacultyMouseEntered
        Color clr = new Color(0,55,55);
        jPanel7.setBackground(clr);
    }//GEN-LAST:event_editfacultyMouseEntered

    private void editfacultyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editfacultyMouseExited
        Color clr = new Color(0,102,102);
        jPanel7.setBackground(clr);
    }//GEN-LAST:event_editfacultyMouseExited

    private void searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseEntered
        Color clr = new Color(0,55,55);
        jPanel8.setBackground(clr);
    }//GEN-LAST:event_searchMouseEntered

    private void searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseExited
        Color clr = new Color(0,102,102);
        jPanel8.setBackground(clr);
    }//GEN-LAST:event_searchMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        Color clr = new Color(0,55,55);
        jPanel9.setBackground(clr);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        Color clr = new Color(0,102,102);
        jPanel9.setBackground(clr);
    }//GEN-LAST:event_logoutMouseExited

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
  home h = new home();
        h.setVisible(true);
        this.setVisible(false);    }//GEN-LAST:event_HomeMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
 Login_Panel lp = new Login_Panel();
        lp.setVisible(true);
        this.setVisible(false);    }//GEN-LAST:event_logoutMouseClicked

    private void addfacultyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addfacultyMouseClicked
        add_faculty af = new add_faculty();
        af.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addfacultyMouseClicked

    private void submitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseEntered
        Color clr = new Color(0,102,102);
        jPanel2.setBackground(clr);
    }//GEN-LAST:event_submitMouseEntered

    private void submitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseExited
        Color clr = new Color(0,153,153);
        jPanel2.setBackground(clr);
    }//GEN-LAST:event_submitMouseExited

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
         try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection  con = DriverManager.getConnection("jdbc:mysql://localhost:3306/collegedata?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "root");
            String fname = txtfname.getText();
            String lname = txtlname.getText();
            String cno=txtcno.getText();
            String email = txtemail.getText();
            String city = txtcity.getText();
            String state = txtstate.getText();
            String gender = txtgender.getText();
            String addate = txtadddate.getText();
            String faname = txtfaname.getText();
            String coursename = txtcoursename.getText();
            String foccupation = txtfoccupation.getText();
            String mname = txtmname.getText();
            String moccupation = txtmoccupation.getText();
            String password = txtpassword.getText();
            String dob = txtdob.getText();
            String branch = txtbranch.getText();
            String osub = txtosub.getText();
            String busno = txtbusno.getText();
            String classs = txtclass.getText();
            String sem = txtsem.getText();
            String sid ="MUS"+fname.charAt(0)+cno.charAt(7)+cno.charAt(8)+cno.charAt(9);
            Statement smt = con.createStatement();
            smt.executeUpdate( "insert into students (sid,firstname,lastname,coursename,optionalsubject,emailid,contactno,dob,gender,state,city,fname,focupation,mname,moccupation,password,adddate,busno,class,sem,branch) values('"+sid+"','"+fname+"','"+lname+"','"+coursename+"','"+osub+"','"+email+"','"+cno+"','"+dob+"','"+gender+"','"+state+"','"+city+"','"+faname+"','"+foccupation+"','"+mname+"','"+moccupation+"','"+password+"','"+addate+"','"+busno+"','"+classs+"','"+sem+"','"+branch+"');");
            JOptionPane.showMessageDialog(this, "Student details saved sucessfully \n Please save "+sid+"for further search");
            txtemail.setText("");
            txtfname.setText("");
            txtlname.setText("");            
            txtcity.setText("");
            txtcno.setText("");
            txtstate.setText("");
            txtgender.setText("");
            txtadddate.setText("");
            txtpassword.setText("");
            txtdob.setText("");
            txtcoursename.setText("");
            txtosub.setText("");
            txtbusno.setText("");
            txtclass.setText("");
            txtsem.setText("");
            txtbranch.setText("");
            txtfaname.setText("");
            txtmname.setText("");
            txtmoccupation.setText("");
            txtfoccupation.setText("");
            
            con.close();
            smt.close();

        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_submitMouseClicked

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
            Search s= new Search();
            s.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_searchMouseClicked

    private void editfacultyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editfacultyMouseClicked
        Edit_faculty ef = new Edit_faculty();
        ef.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_editfacultyMouseClicked

    private void editstudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editstudentMouseClicked
        Edit_student es = new Edit_student();
        es.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_editstudentMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Home;
    private javax.swing.JLabel course;
    private javax.swing.JLabel editfaculty;
    private javax.swing.JLabel editstudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel search;
    private javax.swing.JLabel submit;
    private javax.swing.JTextField txtadddate;
    private javax.swing.JTextField txtbranch;
    private javax.swing.JTextField txtbusno;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtclass;
    private javax.swing.JTextField txtcno;
    private javax.swing.JTextField txtcoursename;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfaname;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtfoccupation;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtmname;
    private javax.swing.JTextField txtmoccupation;
    private javax.swing.JTextField txtosub;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtpic;
    private javax.swing.JTextField txtsem;
    private javax.swing.JTextField txtstate;
    // End of variables declaration//GEN-END:variables
}
