/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrames;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author divya
 */
public class course extends javax.swing.JFrame {

    /**
     * Creates new form course
     */
    public course() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtcredit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txttsoy = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtsoy = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtcoursename = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtcoursecode = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        submit = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        update = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        delete = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        search1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        addfaculty = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Home = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        editstudent = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        editfaculty = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        search = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total credit");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 130, 30));

        txtcredit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtcredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 180, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total sem or year ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 160, 30));

        txttsoy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txttsoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 180, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sem or year");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 130, 30));

        txtsoy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtsoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 180, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Course name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 130, 30));

        txtcoursename.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtcoursename, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 180, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Course Code");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 130, 30));

        txtcoursecode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtcoursecode, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 180, 30));

        jPanel10.setBackground(new java.awt.Color(0, 153, 153));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submit.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("        Add");
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                submitMouseExited(evt);
            }
        });
        jPanel10.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 120, 40));

        jPanel11.setBackground(new java.awt.Color(0, 153, 153));
        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        update.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("      Update");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        jPanel11.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, 120, 40));

        jPanel12.setBackground(new java.awt.Color(0, 153, 153));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        delete.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("      Delete");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteMouseExited(evt);
            }
        });
        jPanel12.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, 120, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Course Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 240, -1));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        search1.setForeground(new java.awt.Color(255, 255, 255));
        search1.setText("      Search");
        search1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                search1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                search1MouseExited(evt);
            }
        });
        jPanel2.add(search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, 120, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 620, 650));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addfaculty.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        addfaculty.setForeground(new java.awt.Color(255, 255, 255));
        addfaculty.setIcon(new javax.swing.ImageIcon("C:\\Users\\divya\\Downloads\\myicons\\icons8-teacher-64.png")); // NOI18N
        addfaculty.setText("Add Faculty");
        addfaculty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addfacultyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addfacultyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addfacultyMouseExited(evt);
            }
        });
        jPanel4.add(addfaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 70));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 170, 70));

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setIcon(new javax.swing.ImageIcon("C:\\Users\\divya\\Downloads\\myicons\\icons8-home-page-100.png")); // NOI18N
        Home.setText("Home");
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeMouseExited(evt);
            }
        });
        jPanel5.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 70));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 170, 70));

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editstudent.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        editstudent.setForeground(new java.awt.Color(255, 255, 255));
        editstudent.setIcon(new javax.swing.ImageIcon("C:\\Users\\divya\\Downloads\\myicons\\icons8-edit-50.png")); // NOI18N
        editstudent.setText("Edit Student");
        editstudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editstudentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editstudentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editstudentMouseExited(evt);
            }
        });
        jPanel6.add(editstudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 70));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 170, 70));

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editfaculty.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        editfaculty.setForeground(new java.awt.Color(255, 255, 255));
        editfaculty.setIcon(new javax.swing.ImageIcon("C:\\Users\\divya\\Downloads\\myicons\\icons8-edit-profile-80.png")); // NOI18N
        editfaculty.setText("Edit Faculty");
        editfaculty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editfacultyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editfacultyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editfacultyMouseExited(evt);
            }
        });
        jPanel7.add(editfaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 180, 70));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 170, 70));

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setIcon(new javax.swing.ImageIcon("C:\\Users\\divya\\Downloads\\myicons\\icons8-search-more-100.png")); // NOI18N
        search.setText("Search");
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchMouseExited(evt);
            }
        });
        jPanel8.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 70));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 170, 70));

        jPanel9.setBackground(new java.awt.Color(0, 102, 102));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("            Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        jPanel9.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 70));

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 170, 70));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 650));

        setSize(new java.awt.Dimension(855, 657));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addfacultyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addfacultyMouseClicked
        add_faculty af = new add_faculty();
        af.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addfacultyMouseClicked

    private void addfacultyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addfacultyMouseEntered
        Color clr = new Color(0,55,55);
        jPanel4.setBackground(clr);
    }//GEN-LAST:event_addfacultyMouseEntered

    private void addfacultyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addfacultyMouseExited
        Color clr = new Color(0,102,102);
        jPanel4.setBackground(clr);
    }//GEN-LAST:event_addfacultyMouseExited

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        home h = new home();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HomeMouseClicked

    private void HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseEntered
        Color clr = new Color(0,55,55);
        jPanel5.setBackground(clr);
    }//GEN-LAST:event_HomeMouseEntered

    private void HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseExited
        Color clr = new Color(0,102,102);
        jPanel5.setBackground(clr);
    }//GEN-LAST:event_HomeMouseExited

    private void editstudentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editstudentMouseEntered
        Color clr = new Color(0,55,55);
        jPanel6.setBackground(clr);
    }//GEN-LAST:event_editstudentMouseEntered

    private void editstudentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editstudentMouseExited
        Color clr = new Color(0,102,102);
        jPanel6.setBackground(clr);
    }//GEN-LAST:event_editstudentMouseExited

    private void editfacultyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editfacultyMouseEntered
        Color clr = new Color(0,55,55);
        jPanel7.setBackground(clr);
    }//GEN-LAST:event_editfacultyMouseEntered

    private void editfacultyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editfacultyMouseExited
        Color clr = new Color(0,102,102);
        jPanel7.setBackground(clr);
    }//GEN-LAST:event_editfacultyMouseExited

    private void searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseEntered
        Color clr = new Color(0,55,55);
        jPanel8.setBackground(clr);
    }//GEN-LAST:event_searchMouseEntered

    private void searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseExited
        Color clr = new Color(0,102,102);
        jPanel8.setBackground(clr);
    }//GEN-LAST:event_searchMouseExited

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Login_Panel lp = new Login_Panel();
        lp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        Color clr = new Color(0,55,55);
        jPanel9.setBackground(clr);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        Color clr = new Color(0,102,102);
        jPanel9.setBackground(clr);
    }//GEN-LAST:event_logoutMouseExited

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection  con = DriverManager.getConnection("jdbc:mysql://localhost:3306/collegedata?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "root");
            String code = txtcoursecode.getText();
            String cname=txtcoursename.getText();
            String soy = txtsoy.getText();
            String tsoy = txttsoy.getText();
            String tcredit = txtcredit.getText();
            Statement smt = con.createStatement();
           smt.executeUpdate( "insert into course (coursecode, coursename, yearorsem, totalyearorsem, totalcredit) values('"+code+"', '"+cname+"', '"+soy+"', '"+tsoy+"', '"+tcredit+"' );");                                                                                                                                                              
            JOptionPane.showMessageDialog(this, "Course details saved sucessfully. ");
            txtcoursecode.setText("");
            txtcoursename.setText("");
            txtsoy.setText("");
            txttsoy.setText("");
            txtcredit.setText("");
            con.close();
            smt.close();
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_submitMouseClicked

    private void submitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseEntered
        Color clr = new Color(0,102,102);
        jPanel10.setBackground(clr);
    }//GEN-LAST:event_submitMouseEntered

    private void submitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseExited
        Color clr = new Color(0,153,153);
         jPanel10.setBackground(clr);
    }//GEN-LAST:event_submitMouseExited

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
          
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        
            Connection  con = DriverManager.getConnection("jdbc:mysql://localhost:3306/collegedata?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "root");
            String code = txtcoursecode.getText();
            String cname=txtcoursename.getText();
            String soy = txtsoy.getText();
            String tsoy = txttsoy.getText();
            String tcredit = txtcredit.getText();
            Statement smt = con.createStatement();
             String quary = "select coursecode from course where coursecode = '"+code+"';";
            ResultSet rs = smt.executeQuery(quary);
            if(rs.next())
            {
                 try
                {
            smt.executeUpdate("update course set coursename='"+cname+"',yearorsem='"+soy+"',totalyearorsem='"+tsoy+"',totalcredit='"+tcredit+"' where coursecode = '"+code+"';");                                                                                                                                                                                                                                                                                                                                  
            JOptionPane.showMessageDialog(this, "Course details updated sucessfully");
            txtcoursecode.setText("");
            txtcoursename.setText("");
            txtsoy.setText("");
            txttsoy.setText("");
            txtcredit.setText("");
            con.close();
            smt.close();
                }
                catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
                
            }
         
          else{
     JOptionPane.showMessageDialog(this, "Please enter right coursecode ");
            }
          } 
          catch (ClassNotFoundException ex) {
            Logger.getLogger(course.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(course.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateMouseClicked

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
        Color clr = new Color(0,102,102);
        jPanel11.setBackground(clr);
    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
        Color clr = new Color(0,153,153);
         jPanel11.setBackground(clr);
    }//GEN-LAST:event_updateMouseExited

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
      try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection  con = DriverManager.getConnection("jdbc:mysql://localhost:3306/collegedata?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "root");
            String code = txtcoursecode.getText();
            Statement smt = con.createStatement();
             String quary = "select coursecode from course where coursecode= '"+code+"';";
            ResultSet rs = smt.executeQuery(quary);
            if(rs.next())
            {
                 try
                {
            smt.executeUpdate("delete from course where coursecode ='"+code+"';");                                                                                                                                                                                                                                                                                                                                  
            JOptionPane.showMessageDialog(this, "Course deleted sucessfully.");
            txtcoursecode.setText("");
            con.close();
            smt.close();
                }
                catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
   }
         else{
     JOptionPane.showMessageDialog(this, "Please enter a coursecode ");
            }
          } 
          catch (ClassNotFoundException ex) {
            Logger.getLogger(course.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(course.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteMouseClicked

    private void deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseEntered
     Color clr = new Color(0,102,102);
        jPanel12.setBackground(clr);
    }//GEN-LAST:event_deleteMouseEntered

    private void deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseExited
         Color clr = new Color(0,153,153);
         jPanel12.setBackground(clr);
    }//GEN-LAST:event_deleteMouseExited

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        Search s = new Search();
        s.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_searchMouseClicked

    private void editfacultyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editfacultyMouseClicked
        Edit_faculty ef = new Edit_faculty();
        ef.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_editfacultyMouseClicked

    private void editstudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editstudentMouseClicked
        Edit_student es = new Edit_student();
        es.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_editstudentMouseClicked

    private void search1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search1MouseEntered
            Color clr = new Color(0,102,102);
        jPanel2.setBackground(clr);
    }//GEN-LAST:event_search1MouseEntered

    private void search1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search1MouseExited
           Color clr = new Color(0,153,153);
         jPanel2.setBackground(clr);
    }//GEN-LAST:event_search1MouseExited

    private void search1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search1MouseClicked
        String f = JOptionPane.showInputDialog(this,"Enter a course code.");
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection  con = DriverManager.getConnection("jdbc:mysql://localhost:3306/collegedata?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "root");
            PreparedStatement pst ;
            ResultSet rst;
            pst = con.prepareStatement("select * from course where coursecode=?");
            pst.setString(1,f);
            rst = pst.executeQuery();
            if(rst.next())
            {
                txtcoursecode.setText(rst.getString(1));
                txtcoursename.setText(rst.getString(2));
                txtsoy.setText(rst.getString(3));
                txttsoy.setText(rst.getString(4));
                txtcredit.setText(rst.getString(5));
             }
            else
            {
                 JOptionPane.showMessageDialog(this, "Please enter a course code");
            }
       } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Edit_faculty.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_search1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new course().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Home;
    private javax.swing.JLabel addfaculty;
    private javax.swing.JLabel delete;
    private javax.swing.JLabel editfaculty;
    private javax.swing.JLabel editstudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel search;
    private javax.swing.JLabel search1;
    private javax.swing.JLabel submit;
    private javax.swing.JTextField txtcoursecode;
    private javax.swing.JTextField txtcoursename;
    private javax.swing.JTextField txtcredit;
    private javax.swing.JTextField txtsoy;
    private javax.swing.JTextField txttsoy;
    private javax.swing.JLabel update;
    // End of variables declaration//GEN-END:variables
}
