package JFrames;

import java.awt.*;

public class home extends javax.swing.JFrame {

    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        addattendance = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        addfaculty = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        addstudent = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        editfaculty = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        editstudent = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        search = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        editbus = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        editcourse = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        editmarks = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addattendance.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        addattendance.setForeground(new java.awt.Color(255, 255, 255));
        addattendance.setIcon(new javax.swing.ImageIcon("C:\\Users\\divya\\Downloads\\myicons\\icons8-attendance-64.png")); // NOI18N
        addattendance.setText("   Attandance");
        addattendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addattendanceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addattendanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addattendanceMouseExited(evt);
            }
        });
        jPanel3.add(addattendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 130));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 210, 130));

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addfaculty.setBackground(new java.awt.Color(255, 255, 255));
        addfaculty.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        addfaculty.setForeground(new java.awt.Color(255, 255, 255));
        addfaculty.setIcon(new javax.swing.ImageIcon("C:\\Users\\divya\\Downloads\\myicons\\icons8-teacher-64.png")); // NOI18N
        addfaculty.setText("  Add Faculty");
        addfaculty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addfacultyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addfacultyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addfacultyMouseExited(evt);
            }
        });
        jPanel4.add(addfaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 200, 130));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 210, 130));

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addstudent.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        addstudent.setForeground(new java.awt.Color(255, 255, 255));
        addstudent.setIcon(new javax.swing.ImageIcon("C:\\Users\\divya\\Downloads\\myicons\\icons8-student-64.png")); // NOI18N
        addstudent.setText(" Add Student");
        addstudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addstudentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addstudentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addstudentMouseExited(evt);
            }
        });
        jPanel5.add(addstudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 130));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 210, 130));

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editfaculty.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        editfaculty.setForeground(new java.awt.Color(255, 255, 255));
        editfaculty.setIcon(new javax.swing.ImageIcon("C:\\Users\\divya\\Downloads\\myicons\\icons8-edit-profile-80.png")); // NOI18N
        editfaculty.setText(" Edit Faculty");
        editfaculty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editfacultyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editfacultyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editfacultyMouseExited(evt);
            }
        });
        jPanel6.add(editfaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 130));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 210, 130));

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editstudent.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        editstudent.setForeground(new java.awt.Color(255, 255, 255));
        editstudent.setIcon(new javax.swing.ImageIcon("C:\\Users\\divya\\Downloads\\myicons\\icons8-edit-50.png")); // NOI18N
        editstudent.setText("     Edit Student");
        editstudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editstudentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editstudentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editstudentMouseExited(evt);
            }
        });
        jPanel7.add(editstudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 200, 130));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 210, 130));

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("   Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        jPanel8.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 80));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, 140, 80));

        jPanel10.setBackground(new java.awt.Color(0, 102, 102));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setIcon(new javax.swing.ImageIcon("C:\\Users\\divya\\Downloads\\myicons\\icons8-search-more-100.png")); // NOI18N
        search.setText(" Search");
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchMouseExited(evt);
            }
        });
        jPanel10.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 130));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 210, 130));

        jPanel11.setBackground(new java.awt.Color(0, 102, 102));
        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editbus.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        editbus.setForeground(new java.awt.Color(255, 255, 255));
        editbus.setIcon(new javax.swing.ImageIcon("C:\\Users\\divya\\Downloads\\myicons\\icons8-school-bus-64.png")); // NOI18N
        editbus.setText("      Bus");
        editbus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editbusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editbusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editbusMouseExited(evt);
            }
        });
        jPanel11.add(editbus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 130));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 210, 130));

        jPanel12.setBackground(new java.awt.Color(0, 102, 102));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editcourse.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        editcourse.setForeground(new java.awt.Color(255, 255, 255));
        editcourse.setIcon(new javax.swing.ImageIcon("C:\\Users\\divya\\Downloads\\myicons\\icons8-book-66.png")); // NOI18N
        editcourse.setText("    Course");
        editcourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editcourseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editcourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editcourseMouseExited(evt);
            }
        });
        jPanel12.add(editcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 130));

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 210, 130));

        jPanel13.setBackground(new java.awt.Color(0, 102, 102));
        jPanel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editmarks.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        editmarks.setForeground(new java.awt.Color(255, 255, 255));
        editmarks.setIcon(new javax.swing.ImageIcon("C:\\Users\\divya\\Downloads\\myicons\\icons8-marks-card-100.png")); // NOI18N
        editmarks.setText("   Marks");
        editmarks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editmarksMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editmarksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editmarksMouseExited(evt);
            }
        });
        jPanel13.add(editmarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 130));

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, 210, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 152, 1002, 670));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Medi-Caps University");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 400, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("A. B. Road, Pigdamber, Rau Indore - 453331\t");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 400, 20));

        jPanel9.setBackground(new java.awt.Color(0, 102, 102));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\divya\\Downloads\\myicons\\medicaps logo.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1002, 155));

        setSize(new java.awt.Dimension(966, 827));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addattendanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addattendanceMouseEntered
        Color clr = new Color(0,55,55);
        jPanel3.setBackground(clr);
    }//GEN-LAST:event_addattendanceMouseEntered

    private void addattendanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addattendanceMouseExited
          Color clr = new Color(0,102,102);
        jPanel3.setBackground(clr);
    }//GEN-LAST:event_addattendanceMouseExited

    private void addfacultyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addfacultyMouseEntered
        Color clr = new Color(0,55,55);
        jPanel4.setBackground(clr);
    }//GEN-LAST:event_addfacultyMouseEntered

    private void addfacultyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addfacultyMouseExited
          Color clr = new Color(0,102,102);
        jPanel4.setBackground(clr);
    }//GEN-LAST:event_addfacultyMouseExited

    private void addstudentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addstudentMouseEntered
        Color clr = new Color(0,55,55);
        jPanel5.setBackground(clr);
    }//GEN-LAST:event_addstudentMouseEntered

    private void addstudentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addstudentMouseExited
         Color clr = new Color(0,102,102);
        jPanel5.setBackground(clr);
    }//GEN-LAST:event_addstudentMouseExited

    private void editfacultyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editfacultyMouseEntered
        Color clr = new Color(0,55,55);
        jPanel6.setBackground(clr);
    }//GEN-LAST:event_editfacultyMouseEntered

    private void editfacultyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editfacultyMouseExited
        Color clr = new Color(0,102,102);
        jPanel6.setBackground(clr);
    }//GEN-LAST:event_editfacultyMouseExited

    private void editstudentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editstudentMouseEntered
        Color clr = new Color(0,55,55);
        jPanel7.setBackground(clr);
    }//GEN-LAST:event_editstudentMouseEntered

    private void editstudentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editstudentMouseExited
        Color clr = new Color(0,102,102);
        jPanel7.setBackground(clr);
    }//GEN-LAST:event_editstudentMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
       Color clr = new Color(0,55,55);
        jPanel8.setBackground(clr);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
          Color clr = new Color(0,102,102);
        jPanel8.setBackground(clr);
    }//GEN-LAST:event_logoutMouseExited

    private void searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseEntered
       Color clr = new Color(0,55,55);
        jPanel10.setBackground(clr);
    }//GEN-LAST:event_searchMouseEntered

    private void searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseExited
         Color clr = new Color(0,102,102);
        jPanel10.setBackground(clr);
    }//GEN-LAST:event_searchMouseExited

    private void editbusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editbusMouseEntered
           Color clr = new Color(0,55,55);
        jPanel11.setBackground(clr);
    }//GEN-LAST:event_editbusMouseEntered

    private void editbusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editbusMouseExited
         Color clr = new Color(0,102,102);
        jPanel11.setBackground(clr);
    }//GEN-LAST:event_editbusMouseExited

    private void editcourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editcourseMouseEntered
           Color clr = new Color(0,55,55);
        jPanel12.setBackground(clr);
    }//GEN-LAST:event_editcourseMouseEntered

    private void editcourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editcourseMouseExited
         Color clr = new Color(0,102,102);
        jPanel12.setBackground(clr);
    }//GEN-LAST:event_editcourseMouseExited

    private void editmarksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editmarksMouseEntered
           Color clr = new Color(0,55,55);
        jPanel13.setBackground(clr);
    }//GEN-LAST:event_editmarksMouseEntered

    private void editmarksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editmarksMouseExited
         Color clr = new Color(0,102,102);
        jPanel13.setBackground(clr);
    }//GEN-LAST:event_editmarksMouseExited

    private void addfacultyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addfacultyMouseClicked
        add_faculty af = new add_faculty();
        af.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addfacultyMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Login_Panel lp = new Login_Panel();
        lp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutMouseClicked

    private void addstudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addstudentMouseClicked
       add_student as = new add_student();
       as.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_addstudentMouseClicked

    private void addattendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addattendanceMouseClicked
       add_attandance aa = new add_attandance();
       aa.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_addattendanceMouseClicked

    private void editcourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editcourseMouseClicked
       course c = new course();
       c.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_editcourseMouseClicked

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        Search s = new Search();
        s.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_searchMouseClicked

    private void editbusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editbusMouseClicked
        Bus b = new Bus();
        b.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_editbusMouseClicked

    private void editmarksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editmarksMouseClicked
        Marks m = new Marks();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_editmarksMouseClicked

    private void editfacultyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editfacultyMouseClicked
            Edit_faculty ef = new Edit_faculty();
            ef.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_editfacultyMouseClicked

    private void editstudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editstudentMouseClicked
            Edit_student es = new Edit_student();
            es.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_editstudentMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addattendance;
    private javax.swing.JLabel addfaculty;
    private javax.swing.JLabel addstudent;
    private javax.swing.JLabel editbus;
    private javax.swing.JLabel editcourse;
    private javax.swing.JLabel editfaculty;
    private javax.swing.JLabel editmarks;
    private javax.swing.JLabel editstudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel search;
    // End of variables declaration//GEN-END:variables
}
