/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrames;
import java.awt.*;

public class Search extends javax.swing.JFrame {

    /**
     * Creates new form Search
     */
    public Search() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        faculty = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        student = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        editbus = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        editcourse = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        editmarks = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        faculty.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        faculty.setForeground(new java.awt.Color(255, 255, 255));
        faculty.setIcon(new javax.swing.ImageIcon("C:\\Users\\divya\\Downloads\\myicons\\icons8-teacher-64.png")); // NOI18N
        faculty.setText("     Faculty");
        faculty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facultyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                facultyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                facultyMouseExited(evt);
            }
        });
        jPanel6.add(faculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 200, 130));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 210, 130));

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        student.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        student.setForeground(new java.awt.Color(255, 255, 255));
        student.setIcon(new javax.swing.ImageIcon("C:\\Users\\divya\\Downloads\\myicons\\icons8-student-64.png")); // NOI18N
        student.setText("     Student");
        student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studentMouseExited(evt);
            }
        });
        jPanel7.add(student, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 200, 130));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 210, 130));

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setIcon(new javax.swing.ImageIcon("C:\\Users\\divya\\Downloads\\myicons\\icons8-home-page-100.png")); // NOI18N
        home.setText("  Home");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });
        jPanel8.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 130));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 210, 130));

        jPanel11.setBackground(new java.awt.Color(0, 102, 102));
        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editbus.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        editbus.setForeground(new java.awt.Color(255, 255, 255));
        editbus.setIcon(new javax.swing.ImageIcon("C:\\Users\\divya\\Downloads\\myicons\\icons8-school-bus-64.png")); // NOI18N
        editbus.setText("      Bus");
        editbus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editbusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editbusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editbusMouseExited(evt);
            }
        });
        jPanel11.add(editbus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 130));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 210, 130));

        jPanel12.setBackground(new java.awt.Color(0, 102, 102));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editcourse.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        editcourse.setForeground(new java.awt.Color(255, 255, 255));
        editcourse.setIcon(new javax.swing.ImageIcon("C:\\Users\\divya\\Downloads\\myicons\\icons8-book-66.png")); // NOI18N
        editcourse.setText("    Course");
        editcourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editcourseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editcourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editcourseMouseExited(evt);
            }
        });
        jPanel12.add(editcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 130));

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 210, 130));

        jPanel13.setBackground(new java.awt.Color(0, 102, 102));
        jPanel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editmarks.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        editmarks.setForeground(new java.awt.Color(255, 255, 255));
        editmarks.setIcon(new javax.swing.ImageIcon("C:\\Users\\divya\\Downloads\\myicons\\icons8-marks-card-100.png")); // NOI18N
        editmarks.setText("   Marks");
        editmarks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editmarksMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editmarksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editmarksMouseExited(evt);
            }
        });
        jPanel13.add(editmarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 130));

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 210, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 152, 950, 460));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("What would you like to search for..........");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 570, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 155));

        setSize(new java.awt.Dimension(956, 613));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void facultyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facultyMouseEntered
        Color clr = new Color(0,55,55);
        jPanel6.setBackground(clr);
    }//GEN-LAST:event_facultyMouseEntered

    private void facultyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facultyMouseExited
        Color clr = new Color(0,102,102);
        jPanel6.setBackground(clr);
    }//GEN-LAST:event_facultyMouseExited

    private void studentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentMouseEntered
        Color clr = new Color(0,55,55);
        jPanel7.setBackground(clr);
    }//GEN-LAST:event_studentMouseEntered

    private void studentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentMouseExited
        Color clr = new Color(0,102,102);
        jPanel7.setBackground(clr);
    }//GEN-LAST:event_studentMouseExited

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        home h = new home();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeMouseClicked

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        Color clr = new Color(0,55,55);
        jPanel8.setBackground(clr);
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        Color clr = new Color(0,102,102);
        jPanel8.setBackground(clr);
    }//GEN-LAST:event_homeMouseExited

    private void editbusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editbusMouseEntered
        Color clr = new Color(0,55,55);
        jPanel11.setBackground(clr);
    }//GEN-LAST:event_editbusMouseEntered

    private void editbusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editbusMouseExited
        Color clr = new Color(0,102,102);
        jPanel11.setBackground(clr);
    }//GEN-LAST:event_editbusMouseExited

    private void editcourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editcourseMouseClicked
        Search_course c = new Search_course();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_editcourseMouseClicked

    private void editcourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editcourseMouseEntered
        Color clr = new Color(0,55,55);
        jPanel12.setBackground(clr);
    }//GEN-LAST:event_editcourseMouseEntered

    private void editcourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editcourseMouseExited
        Color clr = new Color(0,102,102);
        jPanel12.setBackground(clr);
    }//GEN-LAST:event_editcourseMouseExited

    private void editmarksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editmarksMouseEntered
        Color clr = new Color(0,55,55);
        jPanel13.setBackground(clr);
    }//GEN-LAST:event_editmarksMouseEntered

    private void editmarksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editmarksMouseExited
        Color clr = new Color(0,102,102);
        jPanel13.setBackground(clr);
    }//GEN-LAST:event_editmarksMouseExited

    private void studentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentMouseClicked
        Search_student ss = new Search_student();
        ss.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_studentMouseClicked

    private void facultyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facultyMouseClicked
        Search_faculty sf = new Search_faculty();
        sf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_facultyMouseClicked

    private void editmarksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editmarksMouseClicked
            Search_marks sm = new Search_marks();
            sm.setVisible(true);
            this.setVisible(false);            
    }//GEN-LAST:event_editmarksMouseClicked

    private void editbusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editbusMouseClicked
            Search_bus sb = new Search_bus();
            sb.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_editbusMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel editbus;
    private javax.swing.JLabel editcourse;
    private javax.swing.JLabel editmarks;
    private javax.swing.JLabel faculty;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel student;
    // End of variables declaration//GEN-END:variables
}
